### ISSUE TITLE
OSError: [Errno -9985] Device unavailable

### ISSUE THREAD

**Issue by elhanafi5480** [marxtseng/google-assistant-with-snowboy#1]
hey , thank you for your shared subject.

i get an error that the device unavailable (microphone)
that's occur when a specific program uses the microphone and another stream order to microphone .
did u try that code before

**Comment by elhanafi5480** [comment]
INFO:root:Connecting to embeddedassistant.googleapis.com
INFO:root:Using device model picosmart-picosmart-56m6ij and device id afad99ac-efe0-11e9-80a4-b827eb819c5b
Listening... <hotword>, Press Ctrl+C to exit
Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
Expression 'AlsaOpen( &alsaApi->baseHostApiRep, params, streamDir, &self->pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1904
Expression 'PaAlsaStreamComponent_Initialize( &self->capture, alsaApi, inParams, StreamDirection_In, NULL != callback )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2171
Expression 'PaAlsaStream_Initialize( stream, alsaHostApi, inputParameters, outputParameters, sampleRate, framesPerBuffer, callback, streamFlags, userData )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2840
Traceback (most recent call last):
  File "demo.py", line 469, in <module>
    main()
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/env/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "demo.py", line 466, in main
    listening()
  File "demo.py", line 458, in listening
    detector.start(detected_callback=detectedCallback, sleep_time=0.01)
  File "/home/pi/google-assistant-with-snowboy/raspberrypi/snowboydecoder.py", line 176, in start
    stream_callback=audio_callback)
  File "/home/pi/env/lib/python3.5/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/home/pi/env/lib/python3.5/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9985] Device unavailable

**Comment by Mallinanga** [comment]
Same here
